"""initial schema

Revision ID: 4acc20c7e3ea
Revises: 
Create Date: 2026-03-16 21:06:07.454485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4acc20c7e3ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('message_type', sa.Enum('TEXT', 'IMAGE', 'VIDEO', name='messagetype', native_enum=False), nullable=False),
    sa.Column('message_status', sa.Enum('READ', 'SENT', 'SENDING', 'DELIVERED', 'FAILED', 'DELETED', name='messagestatus', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('diagnosis', 'diagnosis_type',
               existing_type=postgresql.ENUM('VISUAL', 'AUDIO', 'MANUAL', 'HYBRID', name='diagnosistype'),
               type_=sa.Enum('VISUAL', 'AUDIO', 'MANUAL', 'HYBRID', name='diagnosistype', native_enum=False),
               existing_nullable=False)
    op.alter_column('items', 'status',
               existing_type=postgresql.ENUM('OPEN', 'PENDING', 'IN_PROGRESS', 'FIXED', 'UNFIXABLE', 'ARCHIVED', name='itemstatus'),
               type_=sa.Enum('OPEN', 'PENDING', 'IN_PROGRESS', 'FIXED', 'UNFIXABLE', 'ARCHIVED', name='itemstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('jobs', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'COMPLETED', 'VERIFIED', 'DISPUTED', 'CANCELLED', name='jobstatus'),
               type_=sa.Enum('ACTIVE', 'COMPLETED', 'VERIFIED', 'DISPUTED', 'CANCELLED', name='jobstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('offers', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='offerstatus'),
               type_=sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='offerstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('user_skills', 'level',
               existing_type=postgresql.ENUM('BEGINNER', 'INTERMEDIATE', 'EXPERT', 'CERTIFIED_PRO', name='skilllevel'),
               type_=sa.Enum('BEGINNER', 'INTERMEDIATE', 'EXPERT', 'CERTIFIED_PRO', name='skilllevel', native_enum=False),
               existing_nullable=False)
    op.alter_column('user_skills', 'verified_level',
               existing_type=postgresql.ENUM('UNVERIFIED', 'PENDING', 'VERIFIED', 'REJECTED', name='userverifystatus'),
               type_=sa.Enum('UNVERIFIED', 'PENDING', 'VERIFIED', 'REJECTED', name='userverifystatus', native_enum=False),
               existing_nullable=False)
    op.add_column('users', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole', native_enum=False), nullable=False))
    op.alter_column('users', 'user_status',
               existing_type=postgresql.ENUM('VERIFIED', 'ACTIVE', 'BANNED', 'UNVERIFIED', 'SUSPENDED', 'PENDING', name='userstatus'),
               type_=sa.Enum('VERIFIED', 'ACTIVE', 'BANNED', 'UNVERIFIED', 'SUSPENDED', 'PENDING', name='userstatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_status',
               existing_type=sa.Enum('VERIFIED', 'ACTIVE', 'BANNED', 'UNVERIFIED', 'SUSPENDED', 'PENDING', name='userstatus', native_enum=False),
               type_=postgresql.ENUM('VERIFIED', 'ACTIVE', 'BANNED', 'UNVERIFIED', 'SUSPENDED', 'PENDING', name='userstatus'),
               existing_nullable=False)
    op.drop_column('users', 'role')
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.alter_column('user_skills', 'verified_level',
               existing_type=sa.Enum('UNVERIFIED', 'PENDING', 'VERIFIED', 'REJECTED', name='userverifystatus', native_enum=False),
               type_=postgresql.ENUM('UNVERIFIED', 'PENDING', 'VERIFIED', 'REJECTED', name='userverifystatus'),
               existing_nullable=False)
    op.alter_column('user_skills', 'level',
               existing_type=sa.Enum('BEGINNER', 'INTERMEDIATE', 'EXPERT', 'CERTIFIED_PRO', name='skilllevel', native_enum=False),
               type_=postgresql.ENUM('BEGINNER', 'INTERMEDIATE', 'EXPERT', 'CERTIFIED_PRO', name='skilllevel'),
               existing_nullable=False)
    op.alter_column('offers', 'status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='offerstatus', native_enum=False),
               type_=postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='offerstatus'),
               existing_nullable=False)
    op.alter_column('jobs', 'status',
               existing_type=sa.Enum('ACTIVE', 'COMPLETED', 'VERIFIED', 'DISPUTED', 'CANCELLED', name='jobstatus', native_enum=False),
               type_=postgresql.ENUM('ACTIVE', 'COMPLETED', 'VERIFIED', 'DISPUTED', 'CANCELLED', name='jobstatus'),
               existing_nullable=False)
    op.alter_column('items', 'status',
               existing_type=sa.Enum('OPEN', 'PENDING', 'IN_PROGRESS', 'FIXED', 'UNFIXABLE', 'ARCHIVED', name='itemstatus', native_enum=False),
               type_=postgresql.ENUM('OPEN', 'PENDING', 'IN_PROGRESS', 'FIXED', 'UNFIXABLE', 'ARCHIVED', name='itemstatus'),
               existing_nullable=False)
    op.alter_column('diagnosis', 'diagnosis_type',
               existing_type=sa.Enum('VISUAL', 'AUDIO', 'MANUAL', 'HYBRID', name='diagnosistype', native_enum=False),
               type_=postgresql.ENUM('VISUAL', 'AUDIO', 'MANUAL', 'HYBRID', name='diagnosistype'),
               existing_nullable=False)
    op.drop_table('message_attachments')
    op.drop_table('reviews')
    op.drop_table('messages')
    # ### end Alembic commands ###
